[build]
builder = "nixpacks"
buildCommand = "npm install"
startCommand = "npm start"

[deploy]
restartPolicyMaxRetries = 3

[deploy.environment]
PORT = 10000
NODE_ENV = "production"
DATABASE_URL = "postgresql://neondb_owner:npg_wj71UganlVWJ@ep-twilight-credit-agc25ymb-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
DB_SSL = "true"

[build.ignore]
paths = [
  "frontend/**",
  "node_modules/**",
  ".git",
  ".gitignore",
  "README.md",
  "*.md",
  ".env*"
]
